import { Montserrat } from "next/font/google";
import "./globals.css";
import Context from "@/components/custom/Context";
import Navbar from "@/components/custom/Navbar";


import Leftbar from "@/components/custom/Leftbar";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable}  antialiased`}>
        <Context>
          <Navbar />{" "}
          <div className="main-wrapper w-screen h-auto flex ">
            {/* left bar */}
            <Leftbar />
            {/* outlet section */}
            <div className="right w-full">{children}</div>
          </div>
        </Context>
      </body>
    </html>
  );
}
